### PR TITLE
Change bumpversion config to support pre-release versions

### PR DESCRIPTION
**Pull request by gsalgado**

### CODE REVIEW

**Comment by janx** [comment]
Can you add some usage document? We can edit https://github.com/ethereum/pyethapp/wiki/Development:-Versions-and-Releases later.

**Comment by gsalgado** [comment]
Sorry, I created this just to request feedback from @ulope, but I'll add the docs in the meantime anyway

**Comment by ulope** [comment]
@gsalgado Yes that's exactly what I had in mind with #216. Sorry for not doing it myself. 

One thing to note: It seems the bumpversion maintainer has abandoned development but in the meantime there is an apparently active fork called [bump2version](https://github.com/c4urself/bump2version). Maybe this would be a good time to switch to that as well.

**Comment by gsalgado** [comment]
Yeah, I guess that makes sense @ulope. I've updated the references to bumpversion, and once we've used this to cut a new release I'll also update the wiki.

@janx when you have a chance, this is now ready for review

**Comment by janx** [comment]
Looks great! :beer:

**Pull request merged**
