### PR TITLE
Use app.join() instead of waiting for signal

### PR DESCRIPTION
**Pull request by panpilkarz**

### CODE REVIEW

**Comment by heikoheiko** [comment]
What is the reason for this PR?

**Comment by panpilkarz** [comment]
Less code and nicer code.

**Comment by heikoheiko** [comment]
Hm, there was a reason to use signal handlers to control the termination of the process and being able to enter the console. Have you tested, that this is still working as before?

**Comment by panpilkarz** [comment]
Yes, I tested that. Will double check now.

**Comment by heikoheiko** [comment]
Consider to write a test for this
http://click.pocoo.org/5/api/#testing

**Comment by panpilkarz** [comment]
Double checked. Let me know if you can see other side effects.

**Comment by konradkonrad** [comment]
Hey @ms83,
I tried to run from your branch. It seems you forgot some commits? Here is what I get:

```
% pyethapp --data-dir /tmp/pea run
...
Traceback (most recent call last):
  File "/tmp/newenv/bin/pyethapp", line 9, in <module>
    load_entry_point('pyethapp', 'console_scripts', 'pyethapp')()
  File "/tmp/newenv/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/newenv/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/tmp/newenv/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/newenv/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/newenv/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/tmp/newenv/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/pyethapp/pyethapp/app.py", line 215, in run
    app.join()
AttributeError: 'EthApp' object has no attribute 'join'
```

**Comment by panpilkarz** [comment]
@konradkonrad  Are you in sync with `pydevp2p` `develop` branch? `EthApp` inherits from `BaseApp` which has join method. 

https://github.com/ethereum/pydevp2p/blob/develop/devp2p/app.py#L43

**Comment by konradkonrad** [comment]
alright, thanks for the hint :)

**Comment by konradkonrad** [comment]
@heikoheiko not sure, how you want to test this with a click test-runner? pyethapp isn't exactly a one-off app, whose exit code you could test. 

Consider this:

``` python
from click.testing import CliRunner
from pyethapp.app import app

def test_run():
  runner = CliRunner()
  with runner.isolated_filesystem():
    result = runner.invoke(app, ["run"])
    assert result.exit_code == 0
```

It will never return...

**Comment by heikoheiko** [comment]
we want to test the full application. especially config and cli params handling.  
monkeypatching it so, that it will exit after a certain condition should be sufficient to let it exit.

**Pull request closed without merging**
