### PR TITLE
Remove duplicate method in class SyncTask

### PR DESCRIPTION
**Pull request by maurycyp**
I deleted the first version of the method since that is the one that gets overridden.

### CODE REVIEW

**Comment by heikoheiko** [comment]
right, but as said before, this is the method which will be kept after development.

**Comment by heikoheiko** [comment]
the way it currently is, is intended.

**Comment by maurycyp** [comment]
I don't think I've submitted this patch before, but if so, then my bad.

**Comment by heikoheiko** [comment]
ah sorry, my fault, this was a different PR:
https://github.com/ethereum/pyethapp/pull/7

**Pull request closed without merging**
