### PR TITLE
Gracefully handle wrong command line options

### PR DESCRIPTION
**Pull request by inzem77**

### CODE REVIEW

**Comment by ulope** [comment]
I would strongly advise against this "log and `sys.exit()`" approach since it makes using (parts of) pyethapp as a library almost impossible.

Instead proper (i.e. semantically meaningful) exceptions should be raised. Those can then becaught at the "UI" level and handled appropriately.

**Comment by heikoheiko** [comment]
I appreciate the amount of work you put in here. But I need to second Ulo. Sorry for not specifying the task clear enough. 

Also be aware that many `asserts` are there for documentation and development purposes only. Many of those you touched are never raised based on wrong CLI parameters, so out of scope of the issue. 

Let's have a chat on skype on how to rework this.

**Comment by inzem77** [comment]
ok. I understand you. I will try to combine exceptions at logic group and we will discuss their in skype chat

**Comment by inzem77** [comment]
Please, check the new commit 30cc76a
Maybe create DataError instead ValueError for checking of different values ?
For example:
```python
 if t_block.header.hash != b:
    raise ValueError('hash {} of header block must be in blockhashes_chain'.format(t_block.header.hash))
```

**Pull request closed without merging**
