### PR TITLE
keys module location changed

### PR DESCRIPTION
**Pull request by AndreMiras**
This was changed in pyethereum develop
commit:85e2725d494d8b4a16e729fc4b05578abb30bc77

### CODE REVIEW

**Comment by AndreMiras** [comment]
I just realised you recently resolved `test_accounts.py` [recently](https://github.com/ethereum/pyethapp/commit/be6e446fc9325031fe197f7958d2f96bcc26743b), but this PR still `fixes test_account_service.py` and `test_jsonrpc.py`.

**Comment by AndreMiras** [comment]
I've made a new PR that fixes more tests, see #220.

**Comment by janx** [comment]
#220 has been merged, can we close this?

**Comment by AndreMiras** [comment]
Yes I guess so (I'm on mobile phone now).
Thank you!

**Pull request closed without merging**
